// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

using UnityEngine;

namespace PlayStoreScripts
{
    /// Static class used to register achievements ID and unlock achievement
    public static class GooglePlayAchievements
    {
        public const string achievement_never_give_up = "CgkI06WkmfgFEAIQCA"; // <GPGSID>
        public const string achievement_first_step = "CgkI06WkmfgFEAIQBA"; // <GPGSID>
        public const string achievement_trap_master = "CgkI06WkmfgFEAIQBQ"; // <GPGSID>
        public const string achievement_serial_killer = "CgkI06WkmfgFEAIQBg"; // <GPGSID>
        public const string achievement_terror = "CgkI06WkmfgFEAIQAw"; // <GPGSID>
        public const string achievement_friendly_vampire = "CgkI06WkmfgFEAIQAQ"; // <GPGSID>
        public const string achievement_survivor = "CgkI06WkmfgFEAIQBw"; // <GPGSID>

        public static void Unlock(string achievementId)
        {
            if (!PlayServices.usePlayServices)
                return;

            Social.ReportProgress(achievementId, 100.0d, success =>
            {
                // Handle success or not
            });
        }
    }
}